# Generated by Django 5.2.7 on 2025-10-08 00:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_event_id', models.IntegerField(unique=True)),
                ('event_type', models.CharField(choices=[('shot', 'Shot'), ('pass', 'Pass'), ('turnover', 'Turnover')], max_length=20)),
                ('x_ft', models.FloatField(blank=True, null=True)),
                ('y_ft', models.FloatField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app.events',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app.games',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app.players',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app.actions',
                'indexes': [models.Index(fields=['code'], name='app.actions_code_afd319_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShotEvent',
            fields=[
                ('event_id', models.OneToOneField(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.event')),
                ('shot_result', models.CharField(blank=True, max_length=20, null=True)),
                ('points', models.IntegerField(choices=[(0, '0 Points'), (2, '2 Points'), (3, '3 Points')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'db_table': 'app.shot_events',
            },
        ),
        migrations.CreateModel(
            name='TurnoverEvent',
            fields=[
                ('event_id', models.OneToOneField(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.event')),
                ('turnover_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'app.turnover_events',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='action_id',
            field=models.ForeignKey(db_column='action_id', on_delete=django.db.models.deletion.CASCADE, to='app.action'),
        ),
        migrations.AddField(
            model_name='event',
            name='game_id',
            field=models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='app.game'),
        ),
        migrations.AddField(
            model_name='event',
            name='player_id',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='app.player'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app.seasons',
                'indexes': [models.Index(fields=['year_start', 'year_end'], name='app.seasons_year_st_44c962_idx')],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='season_id',
            field=models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.CASCADE, to='app.season'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app.teams',
                'indexes': [models.Index(fields=['name'], name='app.teams_name_eb43e1_idx')],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_home', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_id', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='app.game')),
                ('team_id', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
            options={
                'db_table': 'app.game_teams',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='team_id',
            field=models.ForeignKey(blank=True, db_column='team_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
        migrations.CreateModel(
            name='PassEvent',
            fields=[
                ('event_id', models.OneToOneField(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.event')),
                ('completed_pass', models.BooleanField()),
                ('potential_assist', models.BooleanField(default=False)),
                ('turnover', models.BooleanField(default=False)),
                ('target_player_id', models.ForeignKey(blank=True, db_column='target_player_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_passes', to='app.player')),
            ],
            options={
                'db_table': 'app.pass_events',
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['date'], name='app.games_date_9b368d_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['season_id'], name='app.games_season__3517e5_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team_id'], name='app.players_team_id_66ad05_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['name'], name='app.players_name_0575e1_idx'),
        ),
        migrations.AddIndex(
            model_name='gameteam',
            index=models.Index(fields=['game_id'], name='app.game_te_game_id_a507a5_idx'),
        ),
        migrations.AddIndex(
            model_name='gameteam',
            index=models.Index(fields=['team_id'], name='app.game_te_team_id_6502d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameteam',
            unique_together={('game_id', 'team_id')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['source_event_id'], name='app.events_source__6070f8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['player_id'], name='app.events_player__3e34e6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['game_id'], name='app.events_game_id_457091_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['action_id', 'event_type'], name='app.events_action__42ee72_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['player_id', 'action_id'], name='app.events_player__b07444_idx'),
        ),
    ]
